fix: yaml log check
Signed-off-by: Divyansh Khatri <divyanshkhatri200102@gmail.com>

diff --git a/.github/workflows/reusable-build-extensions-on-linux.yml b/.github/workflows/reusable-build-extensions-on-linux.yml
--- a/.github/workflows/reusable-build-extensions-on-linux.yml
+++ b/.github/workflows/reusable-build-extensions-on-linux.yml
@@ -63,6 +63,12 @@ jobs:
       - name: Ensure git safe directory
         run: |
           git config --global --add safe.directory $(pwd)
+      - name: Verify Piper Dependencies (Debug)
+        if: ${{ contains(matrix.plugin, 'piper') }}
+        run: |
+          echo "Checking for rescued libraries..."
+          ls -l /usr/local/lib/libespeak-ng.a || echo "❌ LibEspeak NOT FOUND"
+          ls -l /usr/local/lib/libucd.a || echo "❌ LibUCD NOT FOUND"
       - name: Build ${{ matrix.plugin }}
         shell: bash
         run: |
